	function(ijs_fileexists)
	function(ijs_fsize)
	function(ijs_fopen)
	function(ijs_fread)
	function(ijs_fread_utf)
	function(ijs_exec_js)
	function(ijs_fclose)
	function(ijs_fread32)
	function(ijs_load)
	function(ijs_save)
	function(v8_exit)
	/// ijs FILE SYSTEM ^^^
	function(yaui_platform)
	function(print)
	function(winapi_get_main_view)
	function(winapi_make_button)
	function(winapi_make_label)
	function(winapi_make_input)
	function(winapi_make_edit)
	function(winapi_make_image)
	function(winapi_make_hview)
	function(winapi_make_vview)
	function(winapi_set_xywh)
	function(winapi_set_text)
	function(winapi_get_text)
	function(winapi_set_font)
	function(winapi_get_app_size)
	function(winapi_show)
	function(winapi_hide)
	function(winapi_set_scroll_area)
	function(winapi_set_scroll_pos)
	function(winapi_get_scroll_pos)
	function(winapi_set_read_only)
	function(winapi_set_timer)
	/// NEW VERSION ^^^
	function(winapi_get_command_line)
	function(winapi_console_only)
	function(winapi_set_onpaint)
	function(winapi_set_onclick)
	function(winapi_blit)
	/// WINAPI ONLY ^^^
if (false) {
	function(winapi_get_xywh)
	function(winapi_alloc_console)
	function(winapi_free_console)
	function(winapi_set_focus)
	function(winapi_scroll_to_bottom)
	function(winapi_clear_view)
	function(example)
	function(winapi_alert)
	function(winapi_create_window)
	function(winapi_get_client_area)
	function(winapi_set_bg_color)
	function(ijs_exec_file_js)
} // if (false)
